base:
  config:
    nacos:
      hostname: ali.sizegang.cn
      port: 8848
    redis:
      hostname: www.sizegang.cn
      port: 16379

spring:
  application:
    name: provider-redis
  main:
    allow-bean-definition-overriding: true
  redis:
    host: ${base.config.redis.hostname}
    port: ${base.config.redis.port}
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 30
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 10
        sentinel:
          master: mymaster
          nodes: ${base.config.redis.hostname}:26379,${base.config.redis.hostname}:26380,${base.config.redis.hostname}:26381

dubbo:
  scan:
    base-packages: com.kevin.cloud.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}
  provider:
    timeout: 5000
redisson:
  master-name: mymaster
  password:
  sentinel-addresses: ${base.config.redis.hostname}:26379,${base.config.redis.hostname}:26380,${base.config.redis.hostname}:26381
  fail-max: 3
  pool-size: 10