/*
SQLyog Ultimate v12.2.6 (64 bit)
MySQL - 5.7.24-log : Database - nacos_devtest
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`nacos_devtest` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `nacos_devtest`;

/*Table structure for table `config_info` */

DROP TABLE IF EXISTS `config_info`;

CREATE TABLE `config_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `content` longtext COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'åˆ›å»ºæ—¶é—´',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'ä¿®æ”¹æ—¶é—´',
  `src_user` text COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'ç§Ÿæˆ·å­—æ®µ',
  `c_desc` varchar(256) COLLATE utf8_bin DEFAULT NULL,
  `c_use` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `effect` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `type` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `c_schema` text COLLATE utf8_bin,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfo_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info';

/*Data for the table `config_info` */

insert  into `config_info`(`id`,`data_id`,`group_id`,`content`,`md5`,`gmt_create`,`gmt_modified`,`src_user`,`src_ip`,`app_name`,`tenant_id`,`c_desc`,`c_use`,`effect`,`type`,`c_schema`) values 

(1,'cloud-message-service-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    rocketmq:\r\n      hostname: www.sizegang.cn\r\n      port: 9876\r\n\r\nspring:\r\n  application:\r\n    name: cloud-message\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: decf2861-e65f-43b4-bb76-9df16200867f\r\n    stream:\r\n      rocketmq:\r\n        binder:\r\n          name-server: ${base.config.rocketmq.hostname}:${base.config.rocketmq.port}\r\n      bindings:\r\n        admin-login-log-topic: {destination: admin-login-log-topic, content-type: application/json}\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.message.service.producer\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10002\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','22c42cdf285333ab1c6de64b452d0d2d','2020-01-22 17:31:27','2020-01-22 17:31:27',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813',NULL,NULL,NULL,'yaml',NULL),

(2,'cloud-upload-service-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: cloud-upload\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4118c96342fc2b4a06d26fb6894f87e4','2020-01-22 17:34:59','2020-01-22 17:34:59',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813',NULL,NULL,NULL,'yaml',NULL),

(3,'message-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    rocketmq:\r\n      hostname: www.sizegang.cn\r\n      port: 9876\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: message\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    stream:\r\n      rocketmq:\r\n        binder:\r\n          name-server: ${base.config.rocketmq.hostname}:${base.config.rocketmq.port}\r\n        bindings:\r\n          admin-login-log-topic: {consumer.orderly: true}\r\n      bindings:\r\n        admin-login-log-topic: {destination: admin-login-log-topic, content-type: text/plain, group: admin-login-log-group, consumer.maxAttempts: 1}\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.message.customer\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nserver:\r\n  port: 20001','8eabed3b34ffcb244707ece70e1a4e8c','2020-01-22 17:35:16','2020-01-22 19:20:21',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null'),

(4,'provider-blog-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-blog\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.provider.domain\r\n  mapper-locations: classpath:mapper/*.xml\r\n# 分页配置\r\npagehelper:\r\n  helper-dialect: mysql\r\n  reasonable: true\r\n  support-methods-arguments: true\r\n  params: count=countSql','b23abc2db4d394ca6905b681f8daacd9','2020-01-22 17:35:34','2020-01-22 17:45:37',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null'),

(5,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n      pool: 5\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.clustername}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service, com.kevin.cloud.provider.repository,com.kevin.cloud.provider.pojo,com.kevin.cloud.provider.config\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','7db6ed7e8d62b6c2401ec877fc15f2be','2020-01-22 17:35:58','2020-01-22 22:50:25',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null'),

(6,'provider-log-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-log\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.provider.domain\r\n  mapper-locations: classpath:mapper/*.xml\r\n# 分页配置\r\npagehelper:\r\n  helper-dialect: mysql\r\n  reasonable: true\r\n  support-methods-arguments: true\r\n  params: count=countSql','9e31f56dc024feeebd6c3110a463aca1','2020-01-22 17:36:26','2020-01-22 17:36:26',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813',NULL,NULL,NULL,'yaml',NULL),

(7,'provider-user-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.user.domain\r\n  mapper-locations: classpath:mapper/*.xml','ff51725a8e1aa9752fbc73c0b43eb313','2020-01-22 17:36:56','2020-01-22 17:36:56',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813',NULL,NULL,NULL,'yaml',NULL),

(8,'service-oauth2-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: 182.92.153.190\r\n      port: 8848\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n    redis:\r\n      hostname: www.sizegang.cn\r\n      port: 16379\r\n\r\nspring:\r\n  application:\r\n    name: service-oauth2\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    jdbc-url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n  redis:\r\n    #单节点配置\r\n    host: ${base.config.redis.hostname}\r\n    port: ${base.config.redis.port}\r\n    #集群配置，生产上使用\r\n    #    cluster:\r\n    #      nodes: ${base.config.redis.hostname}:16379,\r\n    #             ${base.config.redis.hostname}:6391,\r\n    #             ${base.config.redis.hostname}:6392\r\n    #      max-redirects: 3\r\n    #      timeout: 5000\r\n    lettuce:\r\n      pool:\r\n        min-idle: 0\r\n        max-idle: 8\r\n        max-wait: -1ms\r\n        max-active: 8\r\n        #Redis 高可以用集群，如果是基于K8s的方式则不需要配置\r\n        sentinel:\r\n          master: mymaster\r\n          nodes: ${base.config.redis.hostname}:26379,${base.config.redis.hostname}:26380,${base.config.redis.hostname}:26381\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  port: 9001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"\r\n\r\nbusiness:\r\n  oauth2:\r\n    grant_type: password\r\n    client_id: client\r\n    client_secret: secret','61b080777b37cb5419c684178cce1362','2020-01-22 17:37:16','2020-01-24 15:18:41',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null'),

(9,'service-user-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: 182.92.153.190:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service.impl\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://182.92.153.190\r\n    port: 8848\r\n    \r\nfeign:\r\n  sentinel:\r\n    enabled: true\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','f89cfc065f021da23a7ef33a2c68ceb6','2020-01-22 17:37:36','2020-01-24 15:34:35',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null'),

(10,'service-article-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-article\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9003\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4a83891b0540d47f80391764e3324460','2020-01-22 17:42:31','2020-01-22 17:46:45',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null'),

(11,'provider-article-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-article\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.provider.domain\r\n  mapper-locations: classpath:mapper/*.xml\r\n# 分页配置\r\npagehelper:\r\n  helper-dialect: mysql\r\n  reasonable: true\r\n  support-methods-arguments: true\r\n  params: count=countSql','396a6a9d62c37a3fae50399890f644d1','2020-01-22 17:45:04','2020-01-22 17:45:04',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813',NULL,NULL,NULL,'yaml',NULL),

(14,'service-blog-config.yaml','DEFAULT_GROUP','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-blog\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service.impl\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9002\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','672b3eaa6bf5eb8dc99ae63738dfc5b8','2020-01-22 17:49:27','2020-01-24 15:58:31',NULL,'112.224.1.183','','fb409926-dcc5-4426-945f-5d1c5cdf3813','null','null','null','yaml','null');

/*Table structure for table `config_info_aggr` */

DROP TABLE IF EXISTS `config_info_aggr`;

CREATE TABLE `config_info_aggr` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext COLLATE utf8_bin NOT NULL COMMENT 'å†…å®¹',
  `gmt_modified` datetime NOT NULL COMMENT 'ä¿®æ”¹æ—¶é—´',
  `app_name` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'ç§Ÿæˆ·å­—æ®µ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfoaggr_datagrouptenantdatum` (`data_id`,`group_id`,`tenant_id`,`datum_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='å¢žåŠ ç§Ÿæˆ·å­—æ®µ';

/*Data for the table `config_info_aggr` */

/*Table structure for table `config_info_beta` */

DROP TABLE IF EXISTS `config_info_beta`;

CREATE TABLE `config_info_beta` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) COLLATE utf8_bin DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'åˆ›å»ºæ—¶é—´',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'ä¿®æ”¹æ—¶é—´',
  `src_user` text COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'ç§Ÿæˆ·å­—æ®µ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfobeta_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info_beta';

/*Data for the table `config_info_beta` */

/*Table structure for table `config_info_tag` */

DROP TABLE IF EXISTS `config_info_tag`;

CREATE TABLE `config_info_tag` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'åˆ›å»ºæ—¶é—´',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'ä¿®æ”¹æ—¶é—´',
  `src_user` text COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfotag_datagrouptenanttag` (`data_id`,`group_id`,`tenant_id`,`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info_tag';

/*Data for the table `config_info_tag` */

/*Table structure for table `config_tags_relation` */

DROP TABLE IF EXISTS `config_tags_relation`;

CREATE TABLE `config_tags_relation` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`),
  UNIQUE KEY `uk_configtagrelation_configidtag` (`id`,`tag_name`,`tag_type`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_tag_relation';

/*Data for the table `config_tags_relation` */

/*Table structure for table `group_capacity` */

DROP TABLE IF EXISTS `group_capacity`;

CREATE TABLE `group_capacity` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ä¸»é”®ID',
  `group_id` varchar(128) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group IDï¼Œç©ºå­—ç¬¦è¡¨ç¤ºæ•´ä¸ªé›†ç¾¤',
  `quota` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'é…é¢ï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `usage` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'ä½¿ç”¨é‡',
  `max_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'å•ä¸ªé…ç½®å¤§å°ä¸Šé™ï¼Œå•ä½ä¸ºå­—èŠ‚ï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `max_aggr_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'èšåˆå­é…ç½®æœ€å¤§ä¸ªæ•°ï¼Œï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `max_aggr_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'å•ä¸ªèšåˆæ•°æ®çš„å­é…ç½®å¤§å°ä¸Šé™ï¼Œå•ä½ä¸ºå­—èŠ‚ï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `max_history_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'æœ€å¤§å˜æ›´åŽ†å²æ•°é‡',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'åˆ›å»ºæ—¶é—´',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'ä¿®æ”¹æ—¶é—´',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='é›†ç¾¤ã€å„Groupå®¹é‡ä¿¡æ¯è¡¨';

/*Data for the table `group_capacity` */

/*Table structure for table `his_config_info` */

DROP TABLE IF EXISTS `his_config_info`;

CREATE TABLE `his_config_info` (
  `id` bigint(64) unsigned NOT NULL,
  `nid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
  `src_user` text COLLATE utf8_bin,
  `src_ip` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `op_type` char(10) COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'ç§Ÿæˆ·å­—æ®µ',
  PRIMARY KEY (`nid`),
  KEY `idx_gmt_create` (`gmt_create`),
  KEY `idx_gmt_modified` (`gmt_modified`),
  KEY `idx_did` (`data_id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='å¤šç§Ÿæˆ·æ”¹é€ ';

/*Data for the table `his_config_info` */

insert  into `his_config_info`(`id`,`nid`,`data_id`,`group_id`,`app_name`,`content`,`md5`,`gmt_create`,`gmt_modified`,`src_user`,`src_ip`,`op_type`,`tenant_id`) values 

(0,1,'cloud-message-service-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    rocketmq:\r\n      hostname: www.sizegang.cn\r\n      port: 9876\r\n\r\nspring:\r\n  application:\r\n    name: cloud-message\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: decf2861-e65f-43b4-bb76-9df16200867f\r\n    stream:\r\n      rocketmq:\r\n        binder:\r\n          name-server: ${base.config.rocketmq.hostname}:${base.config.rocketmq.port}\r\n      bindings:\r\n        admin-login-log-topic: {destination: admin-login-log-topic, content-type: application/json}\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.message.service.producer\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10002\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','22c42cdf285333ab1c6de64b452d0d2d','2010-05-05 00:00:00','2020-01-22 17:31:27',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,2,'cloud-upload-service-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: cloud-upload\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4118c96342fc2b4a06d26fb6894f87e4','2010-05-05 00:00:00','2020-01-22 17:34:59',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,3,'message-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: cloud-upload\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4118c96342fc2b4a06d26fb6894f87e4','2010-05-05 00:00:00','2020-01-22 17:35:16',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,4,'provider-blog-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: cloud-upload\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4118c96342fc2b4a06d26fb6894f87e4','2010-05-05 00:00:00','2020-01-22 17:35:34',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,5,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: www.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.cluster-name}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.repository\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','977ea11c5614f4633d4c760385e71194','2010-05-05 00:00:00','2020-01-22 17:35:58',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,6,'provider-log-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-log\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.provider.domain\r\n  mapper-locations: classpath:mapper/*.xml\r\n# 分页配置\r\npagehelper:\r\n  helper-dialect: mysql\r\n  reasonable: true\r\n  support-methods-arguments: true\r\n  params: count=countSql','9e31f56dc024feeebd6c3110a463aca1','2010-05-05 00:00:00','2020-01-22 17:36:26',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,7,'provider-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.user.domain\r\n  mapper-locations: classpath:mapper/*.xml','ff51725a8e1aa9752fbc73c0b43eb313','2010-05-05 00:00:00','2020-01-22 17:36:56',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,8,'service-oauth2-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n    redis:\r\n      hostname: www.sizegang.cn\r\n      port: 16379\r\n\r\nspring:\r\n  application:\r\n    name: service-oauth2\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    jdbc-url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n  redis:\r\n    #单节点配置\r\n    host: ${base.config.redis.hostname}\r\n    port: ${base.config.redis.port}\r\n    #集群配置，生产上使用\r\n    #    cluster:\r\n    #      nodes: ${base.config.redis.hostname}:16379,\r\n    #             ${base.config.redis.hostname}:6391,\r\n    #             ${base.config.redis.hostname}:6392\r\n    #      max-redirects: 3\r\n    #      timeout: 5000\r\n    lettuce:\r\n      pool:\r\n        min-idle: 0\r\n        max-idle: 8\r\n        max-wait: -1ms\r\n        max-active: 8\r\n        #Redis 高可以用集群，如果是基于K8s的方式则不需要配置\r\n        sentinel:\r\n          master: mymaster\r\n          nodes: ${base.config.redis.hostname}:26379,${base.config.redis.hostname}:26380,${base.config.redis.hostname}:26381\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  port: 9001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"\r\n\r\nbusiness:\r\n  oauth2:\r\n    grant_type: password\r\n    client_id: client\r\n    client_secret: secret','3388c2c49f15c48c8c23e933dfbc2eeb','2010-05-05 00:00:00','2020-01-22 17:37:16',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,9,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: www.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://www.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','3d26c40534b10d71e6d7a716dcf7e0b4','2010-05-05 00:00:00','2020-01-22 17:37:36',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,10,'service-article-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-article\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','22cb6e0b8e8bae68300ae4614ee34278','2010-05-05 00:00:00','2020-01-22 17:42:31',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,11,'provider-article-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: provider-article\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nmybatis:\r\n  type-aliases-package: com.kevin.cloud.provider.domain\r\n  mapper-locations: classpath:mapper/*.xml\r\n# 分页配置\r\npagehelper:\r\n  helper-dialect: mysql\r\n  reasonable: true\r\n  support-methods-arguments: true\r\n  params: count=countSql','396a6a9d62c37a3fae50399890f644d1','2010-05-05 00:00:00','2020-01-22 17:45:04',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(4,12,'provider-blog-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: cloud-upload\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4118c96342fc2b4a06d26fb6894f87e4','2010-05-05 00:00:00','2020-01-22 17:45:37',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(10,13,'service-article-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-article\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','22cb6e0b8e8bae68300ae4614ee34278','2010-05-05 00:00:00','2020-01-22 17:46:45',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(0,14,'service-blog-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9002\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','a961edba4514d99be04dfc7ab9c0f6cb','2010-05-05 00:00:00','2020-01-22 17:49:27',NULL,'112.224.1.183','I','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(5,15,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: www.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.cluster-name}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.repository\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','977ea11c5614f4633d4c760385e71194','2010-05-05 00:00:00','2020-01-22 18:17:00',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(9,16,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: www.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://www.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','3d26c40534b10d71e6d7a716dcf7e0b4','2010-05-05 00:00:00','2020-01-22 18:20:28',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(5,17,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: www.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n      pool: 5\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.cluster-name}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.repository\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','68841996d7e8591a9ec45bc3d0199790','2010-05-05 00:00:00','2020-01-22 18:22:35',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(5,18,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n      pool: 5\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.cluster-name}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.repository\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','ac24476a8378d87da7a51435135b8940','2010-05-05 00:00:00','2020-01-22 18:50:26',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(5,19,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n      pool: 5\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.clustername}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.repository\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','daefdc1f9caa2524b74cc03c0a21717f','2010-05-05 00:00:00','2020-01-22 19:04:04',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(3,20,'message-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    oauth:\r\n      hostname: localhost\r\n      port: 9001\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n\r\nspring:\r\n  application:\r\n    name: cloud-upload\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token\r\n      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token\r\n\r\nserver:\r\n  port: 10001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','4118c96342fc2b4a06d26fb6894f87e4','2010-05-05 00:00:00','2020-01-22 19:20:21',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(5,21,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n      pool: 5\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.clustername}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider.repository,com.kevin.cloud.provider.service, com.kevin.cloud.provider.util\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','bbc13a808dacd62c6f1c6070f80ea5fa','2010-05-05 00:00:00','2020-01-22 22:46:50',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(5,22,'provider-elasticsearch-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    es:\r\n      hostname: 182.92.153.190\r\n      port: 9300\r\n      cluster-name: es-cluster\r\n      pool: 5\r\n\r\nspring:\r\n  application:\r\n    name: provider-elasticsearch\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  elasticsearch:\r\n    rest:\r\n      uris: [\"http://182.92.153.190:9200\"]\r\n  data:\r\n    elasticsearch:\r\n      cluster-name: ${base.config.es.clustername}\r\n      cluster-nodes: ${base.config.es.hostname}:${base.config.es.port}\r\n      repositories:\r\n        enabled: true\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.provider\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n# 如果不配置\r\n#management:\r\n#  health:\r\n#    elasticsearch:\r\n#      enabled: false\r\n','217ec1ab36ddb96c0a7f6d8eaad1af9c','2010-05-05 00:00:00','2020-01-22 22:50:25',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(9,23,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','b16a9b45a8de5788b87b9cb60900605b','2010-05-05 00:00:00','2020-01-24 13:00:47',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(9,24,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n    \r\nfeign:\r\n  client:\r\n    config:\r\n      feignName:\r\n        connectTimeout: 5000  # 相当于Request.Optionsn 连接超时时间\r\n        readTimeout: 5000     # 相当于Request.Options 读取超时时间\r\n        loggerLevel: full     # 配置Feign的日志级别，相当于代码配置方式中的Logger\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','489dde8166fe342b41247ced6de01a8f','2010-05-05 00:00:00','2020-01-24 13:10:23',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(8,25,'service-oauth2-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    tidb:\r\n      hostname: mysql.sizegang.cn\r\n      port: 3308\r\n    nacos:\r\n      hostname: ali.sizegang.cn\r\n      port: 8848\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n    redis:\r\n      hostname: www.sizegang.cn\r\n      port: 16379\r\n\r\nspring:\r\n  application:\r\n    name: service-oauth2\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n  datasource:\r\n    type: com.zaxxer.hikari.HikariDataSource\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    jdbc-url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/vue_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false\r\n    username: root\r\n    password: root\r\n    hikari:\r\n      minimum-idle: 5\r\n      idle-timeout: 600000\r\n      maximum-pool-size: 10\r\n      auto-commit: true\r\n      pool-name: MyHikariCP\r\n      max-lifetime: 1800000\r\n      connection-timeout: 30000\r\n      connection-test-query: SELECT 1\r\n  redis:\r\n    #单节点配置\r\n    host: ${base.config.redis.hostname}\r\n    port: ${base.config.redis.port}\r\n    #集群配置，生产上使用\r\n    #    cluster:\r\n    #      nodes: ${base.config.redis.hostname}:16379,\r\n    #             ${base.config.redis.hostname}:6391,\r\n    #             ${base.config.redis.hostname}:6392\r\n    #      max-redirects: 3\r\n    #      timeout: 5000\r\n    lettuce:\r\n      pool:\r\n        min-idle: 0\r\n        max-idle: 8\r\n        max-wait: -1ms\r\n        max-active: 8\r\n        #Redis 高可以用集群，如果是基于K8s的方式则不需要配置\r\n        sentinel:\r\n          master: mymaster\r\n          nodes: ${base.config.redis.hostname}:26379,${base.config.redis.hostname}:26380,${base.config.redis.hostname}:26381\r\n\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://${base.config.nacos.hostname}\r\n    port: ${base.config.nacos.port}\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  port: 9001\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"\r\n\r\nbusiness:\r\n  oauth2:\r\n    grant_type: password\r\n    client_id: client\r\n    client_secret: secret','3388c2c49f15c48c8c23e933dfbc2eeb','2010-05-05 00:00:00','2020-01-24 15:18:41',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(9,26,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n    \r\nfeign:\r\n  client:\r\n    config:\r\n      default:\r\n        connectTimeout: 1000 # 相当于Request.Optionsn 连接超时时间\r\n        readTimeout: 5000     # 相当于Request.Options 读取超时时间\r\n        loggerLevel: full     # 配置Feign的日志级别，相当于代码配置方式中的Logger\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','238c72064a0ecb9033d59deabaa4fb00','2010-05-05 00:00:00','2020-01-24 15:19:11',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(9,27,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: 182.92.153.190:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://182.92.153.190\r\n    port: 8848\r\n    \r\nfeign:\r\n  client:\r\n    config:\r\n      default:\r\n        connectTimeout: 1000 # 相当于Request.Optionsn 连接超时时间\r\n        readTimeout: 5000     # 相当于Request.Options 读取超时时间\r\n        loggerLevel: full     # 配置Feign的日志级别，相当于代码配置方式中的Logger\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','644a36331e50ef937bae2a6263d5b335','2010-05-05 00:00:00','2020-01-24 15:32:11',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(9,28,'service-user-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: 182.92.153.190:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service.impl\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://182.92.153.190\r\n    port: 8848\r\n    \r\nfeign:\r\n  sentinel:\r\n    enabled: true\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9000\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','f89cfc065f021da23a7ef33a2c68ceb6','2010-05-05 00:00:00','2020-01-24 15:34:35',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813'),

(14,29,'service-blog-config.yaml','DEFAULT_GROUP','','base:\r\n  config:\r\n    sentile:\r\n      hostname: localhost\r\n      port: 8020\r\n\r\nspring:\r\n  application:\r\n    name: service-user\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: ali.sizegang.cn:8848\r\n      config:\r\n        namespace: fb409926-dcc5-4426-945f-5d1c5cdf3813\r\n    sentinel:\r\n      transport:\r\n        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}\r\n\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: client\r\n      client-secret: secret\r\n      access-token-uri: http://localhost:9001/oauth/token\r\n      user-authorization-uri: http://localhost:9001/oauth/authorize\r\n    resource:\r\n      token-info-uri: http://localhost:9001/oauth/check_token\r\ndubbo:\r\n  scan:\r\n    base-packages: com.kevin.cloud.service\r\n  protocol:\r\n    name: dubbo\r\n    port: -1\r\n    serialization: kryo\r\n  registry:\r\n    address: nacos://ali.sizegang.cn\r\n    port: 8848\r\n\r\nfeign:\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  sentinel:\r\n    enabled: true\r\n\r\nserver:\r\n  # ${random.int[9000,9999]} 随机端口\r\n  port: 9002\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \"*\"','a961edba4514d99be04dfc7ab9c0f6cb','2010-05-05 00:00:00','2020-01-24 15:58:31',NULL,'112.224.1.183','U','fb409926-dcc5-4426-945f-5d1c5cdf3813');

/*Table structure for table `roles` */

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `username` varchar(50) NOT NULL,
  `role` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `roles` */

insert  into `roles`(`username`,`role`) values 

('nacos','ROLE_ADMIN');

/*Table structure for table `tenant_capacity` */

DROP TABLE IF EXISTS `tenant_capacity`;

CREATE TABLE `tenant_capacity` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ä¸»é”®ID',
  `tenant_id` varchar(128) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'é…é¢ï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `usage` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'ä½¿ç”¨é‡',
  `max_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'å•ä¸ªé…ç½®å¤§å°ä¸Šé™ï¼Œå•ä½ä¸ºå­—èŠ‚ï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `max_aggr_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'èšåˆå­é…ç½®æœ€å¤§ä¸ªæ•°',
  `max_aggr_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'å•ä¸ªèšåˆæ•°æ®çš„å­é…ç½®å¤§å°ä¸Šé™ï¼Œå•ä½ä¸ºå­—èŠ‚ï¼Œ0è¡¨ç¤ºä½¿ç”¨é»˜è®¤å€¼',
  `max_history_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'æœ€å¤§å˜æ›´åŽ†å²æ•°é‡',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'åˆ›å»ºæ—¶é—´',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT 'ä¿®æ”¹æ—¶é—´',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='ç§Ÿæˆ·å®¹é‡ä¿¡æ¯è¡¨';

/*Data for the table `tenant_capacity` */

/*Table structure for table `tenant_info` */

DROP TABLE IF EXISTS `tenant_info`;

CREATE TABLE `tenant_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) COLLATE utf8_bin DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT 'åˆ›å»ºæ—¶é—´',
  `gmt_modified` bigint(20) NOT NULL COMMENT 'ä¿®æ”¹æ—¶é—´',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_info_kptenantid` (`kp`,`tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='tenant_info';

/*Data for the table `tenant_info` */

insert  into `tenant_info`(`id`,`kp`,`tenant_id`,`tenant_name`,`tenant_desc`,`create_source`,`gmt_create`,`gmt_modified`) values 

(1,'1','fb409926-dcc5-4426-945f-5d1c5cdf3813','vue_blog','vue_blog ','nacos',1579685442380,1579685442380);

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `username` varchar(50) NOT NULL,
  `password` varchar(500) NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `users` */

insert  into `users`(`username`,`password`,`enabled`) values 

('nacos','$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
